# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_service'),
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Service')),
            ],
        ),
    ]
