# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='queue',
            field=models.SlugField(default='', unique=True, verbose_name='Queue'),
            preserve_default=False,
        ),
    ]
