# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.AddField(
            model_name='service',
            name='topic',
            field=models.SlugField(default='', unique=True, verbose_name='Topic'),
            preserve_default=False,
        ),
    ]
